-- Standard College of Education admission letter (modelled on the sample
-- in public/letter-adm.jpg), inserted for every active UG programme that has
-- no active admission letter yet. Edit wording, fees, signatory and upload
-- the signature under AIS > Admission Letters. Safe to re-run.

INSERT INTO ams_letter (id, programId, category, title, signatory, signature, template, status, createdAt, updatedAt)
SELECT UUID(), p.id, 'UG', 'OFFER OF ADMISSION - BACHELOR OF EDUCATION', '<p><strong>PRINCIPAL</strong></p>', '', '<p><strong>OFFER OF ADMISSION TO <u>AKATSI COLLEGE OF EDUCATION</u> (<u>AKATSICO</u>)</strong></p><p><strong>::programme_years_words-YEAR <u>::program_name_big</u> PROGRAMME (::session_year)</strong></p><p><br></p><p>1. With reference to your application, we are pleased to offer you admission to pursue a ::programme_years-year ::program_name programme at Akatsi College of Education.</p><p><br></p><p>2. You will pursue the <strong>::program_name_big</strong> programme. This offer of admission is for the ::session_year academic year only (<strong>cannot be deferred</strong>).</p><p><br></p><p>3. You will be expected to undergo a compulsory <u>campus-based medical examination</u>. Your admission is dependent upon a satisfactory medical report on your state of general health and acceptance of the general conditions attached to the offer.</p><p><br></p><p>4. You are to note that if the College discovers later that you do not possess the qualifications by which you have been offered admission to pursue this programme of study, you will be withdrawn immediately. You will also be held personally liable for any false statement or omission made on your application form.</p><p><br></p><p>5. You will be on <u>probation</u> for the full duration of your programme. Satisfactory academic work and good conduct are required for your continued stay on the programme and you will be required to adhere to all College rules and regulations.</p><p><br></p><p>6. You are required to pay a non-refundable provisional admission fee of <strong>::fee_amount</strong> in full. Additionally, you shall pay a <u>Residential Facilities User Fee</u> of <strong>Five Hundred Ghana Cedis (GH¢500.00)</strong> and an <u>examination fee</u> of <strong>Five Hundred Ghana Cedis (GH¢500.00)</strong> per semester to the mentor university. Each student shall also be required to pay <strong>Thirty Ghana Cedis (GH¢30.00)</strong> towards the Teacher Trainee Association of Ghana (T.T.A.G) National Office Project.</p><p><br></p><p>7. Details on registration, orientation and the start of lectures will be communicated to you. Please bring this letter with you when reporting to the College.</p><p><br></p><p>Please accept our congratulations on your admission.</p><p><br></p><p>Yours faithfully,</p><p>::signature</p><p>::signatory</p>', 1, NOW(3), NOW(3)
FROM ais_program p
WHERE p.category = 'UG' AND p.status = 1
  AND NOT EXISTS (SELECT 1 FROM ams_letter l WHERE l.programId = p.id AND l.status = 1);
